[ENH] improvements to `_check_soft_dependencies`
sktime/skbase pull request #88
Opened 2022-12-28 12:24 UTC by fkiraly

Migrates improvements to `_check_soft_dependencies` from `sktime`:

* https://github.com/sktime/sktime/pull/3925
* https://github.com/sktime/sktime/pull/3955

2022-12-29 18:05 UTC, RNKuhns requested changes
CodeQL item looks legit, so we should fix it.

Also, can we add tests of _check_soft_dependencies?

2022-12-29 18:05 UTC, RNKuhns commented on skbase/testing/utils/_dependencies.py
> +            req = Requirement(package)
This looks valid. `req` is redefined on line 92 before it is used. I think that maybe the try-except block was meant to replace the code on line 92? Either way, one of the use cases probably needs to be deleted.

2022-12-29 19:01 UTC, fkiraly commented on skbase/testing/utils/_dependencies.py
> +            req = Requirement(package)
well, this proves it doesn't only produce garbage! Indeed this is valid. Fixed.

2022-12-29 19:03 UTC, fkiraly commented
> Also, can we add tests of `_check_soft_dependencies`?

Sure! Note, there weren't any to start with, and it is not obvious how to ensure the test condition is constant, because it is always using the environment constructed from `pyproject`.

I can test against that environment (assuming the lower bounds will always stay the same) and some negative cases.

2022-12-29 19:17 UTC, fkiraly commented
Have added tests.

2022-12-30 00:25 UTC, RNKuhns approved these changes
Looks reasonable to me now. I'll merge the main branch in to re-run the tests, and then merge once they pass.

2022-12-30 02:15 UTC, merged